const homedata = {
    state:{
        homerecommend:[//首页推荐
            {
                id:1,
                coverimgurl:"http://wg-bishe.oss-cn-chengdu.aliyuncs.com/workimgs/work1/1.jpg",
                classification:"风景",//分类
                authorid:2,
                authorname:"一炉烟火",
                authorheadurl:"https://image.riba2534.cn/18-12-13/34184894.jpg",
                goodnumber:16,
                isgood:false,
            },
            {
                id:2,
                coverimgurl:"http://wg-bishe.oss-cn-chengdu.aliyuncs.com/workimgs/work1/1.jpg",
                classification:"风景",//分类
                authorid:2,
                authorname:"一炉烟火",
                authorheadurl:"https://image.riba2534.cn/18-12-13/34184894.jpg",
                goodnumber:16,
                isgood:false,
            },
            {
                id:3,
                coverimgurl:"http://wg-bishe.oss-cn-chengdu.aliyuncs.com/workimgs/work1/1.jpg",
                classification:"风景",//分类
                authorid:2,
                authorname:"一炉烟火",
                authorheadurl:"https://image.riba2534.cn/18-12-13/34184894.jpg",
                goodnumber:16,
                isgood:false,
            },            {
                id:4,
                coverimgurl:"http://wg-bishe.oss-cn-chengdu.aliyuncs.com/workimgs/work1/1.jpg",
                classification:"风景",//分类
                authorid:2,
                authorname:"一炉烟火",
                authorheadurl:"https://image.riba2534.cn/18-12-13/34184894.jpg",
                goodnumber:16,
                isgood:false,
            },            
            {
                id:5,
                coverimgurl:"http://wg-bishe.oss-cn-chengdu.aliyuncs.com/workimgs/work1/1.jpg",
                classification:"风景",//分类
                authorid:2,
                authorname:"一炉烟火",
                authorheadurl:"https://image.riba2534.cn/18-12-13/34184894.jpg",
                goodnumber:16,
                isgood:false,
            },
            {
                id:6,
                coverimgurl:"http://wg-bishe.oss-cn-chengdu.aliyuncs.com/workimgs/work1/1.jpg",
                classification:"风景",//分类
                authorid:2,
                authorname:"一炉烟火",
                authorheadurl:"https://image.riba2534.cn/18-12-13/34184894.jpg",
                goodnumber:16,
                isgood:false,
            },
            {
                id:7,
                coverimgurl:"http://wg-bishe.oss-cn-chengdu.aliyuncs.com/workimgs/work1/1.jpg",
                classification:"风景",//分类
                authorid:2,
                authorname:"一炉烟火",
                authorheadurl:"https://image.riba2534.cn/18-12-13/34184894.jpg",
                goodnumber:16,
                isgood:false,
            },
            {
                id:8,
                coverimgurl:"http://wg-bishe.oss-cn-chengdu.aliyuncs.com/workimgs/work1/1.jpg",
                classification:"风景",//分类
                authorid:2,
                authorname:"一炉烟火",
                authorheadurl:"https://image.riba2534.cn/18-12-13/34184894.jpg",
                goodnumber:16,
                isgood:false,
            }
        ],
        homebowen:[//首页博文
            {
                id:1,
                coverimgurl:"http://wg-bishe.oss-cn-chengdu.aliyuncs.com/bowenimgs/1/1.jpg",
                title:"摄影师私藏的8个拍摄道具：你也可以拍摄出杂志感大片",
                smallintroduction:"尽我们所能去创造和发现属于你的“最佳道具”！",
            },
            {
                id:2,
                coverimgurl:"http://wg-bishe.oss-cn-chengdu.aliyuncs.com/bowenimgs/1/1.jpg",
                title:"摄影师私藏的8个拍摄道具：你也可以拍摄出杂志感大片",
                smallintroduction:"尽我们所能去创造和发现属于你的“最佳道具”！",
            },
            {
                id:3,
                coverimgurl:"http://wg-bishe.oss-cn-chengdu.aliyuncs.com/bowenimgs/1/1.jpg",
                title:"摄影师私藏的8个拍摄道具：你也可以拍摄出杂志感大片",
                smallintroduction:"尽我们所能去创造和发现属于你的“最佳道具”！",
            },
            {
                id:4,
                coverimgurl:"http://wg-bishe.oss-cn-chengdu.aliyuncs.com/bowenimgs/1/1.jpg",
                title:"摄影师私藏的8个拍摄道具：你也可以拍摄出杂志感大片",
                smallintroduction:"尽我们所能去创造和发现属于你的“最佳道具”！",
            },
        ],
        photographer:[//热门摄影师
            {
                id:1,
                headurl:"http://wg-bishe.oss-cn-chengdu.aliyuncs.com/headimgs/1.jpg",
                username:"肯迪仔",
                userintroduction:"把摄影作为一项很有价值的事情来做，捕捉生活中能打动自己的人和事，记录瞬间点滴，汇集人间冷暖，用叙事的手法述说人生故事，用真诚的镜头语言描绘人间百态，让影像留住眼中的过往。做有利于古老传统艺术传承的宣传者、记录当下社会的劳动者。",
                coverimgurl:"http://wg-bishe.oss-cn-chengdu.aliyuncs.com/userbgimgs/1.jpg",
            },
            {
                id:5,
                headurl:"http://wg-bishe.oss-cn-chengdu.aliyuncs.com/headimgs/2.jpg",
                username:"ALI-阿敏",
                userintroduction:"把摄影作为一项很有价值的事情来做，捕捉生活中能打动自己的人和事，记录瞬间点滴，汇集人间冷暖，用叙事的手法述说人生故事，用真诚的镜头语言描绘人间百态，让影像留住眼中的过往。做有利于古老传统艺术传承的宣传者、记录当下社会的劳动者。",
                coverimgurl:"http://wg-bishe.oss-cn-chengdu.aliyuncs.com/userbgimgs/2.jpg",
            },
            {
                id:3,
                headurl:"http://wg-bishe.oss-cn-chengdu.aliyuncs.com/headimgs/3.jpg",
                username:"小豪先生",
                userintroduction:"把摄影作为一项很有价值的事情来做，捕捉生活中能打动自己的人和事，记录瞬间点滴，汇集人间冷暖，用叙事的手法述说人生故事，用真诚的镜头语言描绘人间百态，让影像留住眼中的过往。做有利于古老传统艺术传承的宣传者、记录当下社会的劳动者。",
                coverimgurl:"http://wg-bishe.oss-cn-chengdu.aliyuncs.com/userbgimgs/3.jpg",
            },
            {
                id:4,
                headurl:"http://wg-bishe.oss-cn-chengdu.aliyuncs.com/headimgs/4.jpg",
                username:"鸿雁书",
                userintroduction:"把摄影作为一项很有价值的事情来做，捕捉生活中能打动自己的人和事，记录瞬间点滴，汇集人间冷暖，用叙事的手法述说人生故事，用真诚的镜头语言描绘人间百态，让影像留住眼中的过往。做有利于古老传统艺术传承的宣传者、记录当下社会的劳动者。",
                coverimgurl:"http://wg-bishe.oss-cn-chengdu.aliyuncs.com/userbgimgs/4.jpg",
            }
        ],
        photographerwork:[//热门摄影师的作品
            {
                id:9,
                coverimgurl:"http://wg-bishe.oss-cn-chengdu.aliyuncs.com/workimgs/worktest/1.jpg",
                classification:"风景",//分类
                authorid:2,
                authorname:"肯迪仔",
                authorheadurl:"http://wg-bishe.oss-cn-chengdu.aliyuncs.com/headimgs/1.jpg",
                goodnumber:16,
                isgood:false,
            },
            {
                id:10,
                coverimgurl:"http://wg-bishe.oss-cn-chengdu.aliyuncs.com/workimgs/work1/1.jpg",
                classification:"风景",//分类
                authorid:2,
                authorname:"ALI-阿敏",
                authorheadurl:"http://wg-bishe.oss-cn-chengdu.aliyuncs.com/headimgs/2.jpg",
                goodnumber:16,
                isgood:false,
            },
            {
                id:11,
                coverimgurl:"http://wg-bishe.oss-cn-chengdu.aliyuncs.com/workimgs/work1/1.jpg",
                classification:"风景",//分类
                authorid:2,
                authorname:"小豪先生",
                authorheadurl:"http://wg-bishe.oss-cn-chengdu.aliyuncs.com/headimgs/3.jpg",
                goodnumber:16,
                isgood:false,
            },
            {
                id:12,
                coverimgurl:"http://wg-bishe.oss-cn-chengdu.aliyuncs.com/workimgs/work1/1.jpg",
                classification:"风景",//分类
                authorid:2,
                authorname:"鸿雁书",
                authorheadurl:"http://wg-bishe.oss-cn-chengdu.aliyuncs.com/headimgs/4.jpg",
                goodnumber:16,
                isgood:false,
            }
        ],
    },
    mutations:{
         SET_isgood:(state,{id,isgood}) =>{
             for(let x in  state.homerecommend){
                 if( state.homerecommend[x].id == id){
                    state.homerecommend[x].isgood = isgood;
                    if(isgood){
                        state.homerecommend[x].goodnumber+=1;
                    }else{
                        state.homerecommend[x].goodnumber-=1;
                    }
                     break;
                 }
             }
             for(let x in state.photographerwork){
                if( state.photographerwork[x].id == id){
                    state.photographerwork[x].isgood = isgood;
                    if(isgood){
                        state.photographerwork[x].goodnumber+=1;
                    }else{
                        state.photographerwork[x].goodnumber-=1;
                    }
                     break;
                 }
             }
         },
         
    },
    actions:{
        Setisgoodandhome({commit},{id,isgood}){
            commit('SET_isgood',{id,isgood});
            console.log(id+" "+isgood);
            
        }
    }
}
export default homedata